# training options
sampling_rate: 8000
frame_size: 200
frame_shift: 80
model_type: Transformer
max_epochs: 200
gradclip: 5
batchsize: 8
hidden_size: 256
num_frames: 512
num_speakers: 4
input_transform: logmel23
optimizer: noam
lr: 1.0
context_size: 7
subsampling: 10
gradient_accumulation_steps: 1
transformer_encoder_n_heads: 4
transformer_encoder_n_layers: 2
transformer_encoder_dropout: 0.1
noam_warmup_steps: 25000
seed: 777
gpu: 1
